// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz2jcaCWGM12KpVeWNQSyMzD1KfBWYEs8',
    appId: '1:820123248261:web:3af5a9b8418556333eabec',
    messagingSenderId: '820123248261',
    projectId: 'doorcareuser',
    authDomain: 'doorcareuser.firebaseapp.com',
    storageBucket: 'doorcareuser.appspot.com',
    measurementId: 'G-JEEC5THREJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl0rSxBKhZgwyrBOevwha7zz4scgzF6Xw',
    appId: '1:820123248261:android:429ab52050cae3543eabec',
    messagingSenderId: '820123248261',
    projectId: 'doorcareuser',
    storageBucket: 'doorcareuser.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCP_vIYnQmnNsA3Q64I5VbI4ygLUAXoIE',
    appId: '1:820123248261:ios:1b090035ba8719343eabec',
    messagingSenderId: '820123248261',
    projectId: 'doorcareuser',
    storageBucket: 'doorcareuser.appspot.com',
    iosBundleId: 'com.example.doorCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCP_vIYnQmnNsA3Q64I5VbI4ygLUAXoIE',
    appId: '1:820123248261:ios:1b090035ba8719343eabec',
    messagingSenderId: '820123248261',
    projectId: 'doorcareuser',
    storageBucket: 'doorcareuser.appspot.com',
    iosBundleId: 'com.example.doorCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz2jcaCWGM12KpVeWNQSyMzD1KfBWYEs8',
    appId: '1:820123248261:web:bc3d06e71c21490b3eabec',
    messagingSenderId: '820123248261',
    projectId: 'doorcareuser',
    authDomain: 'doorcareuser.firebaseapp.com',
    storageBucket: 'doorcareuser.appspot.com',
    measurementId: 'G-RQ7GNV5PBM',
  );
}
